// Theme Changing Function
function toggledark() {
    var element = document.getElementById("body");
    element.classList.toggle("body-dark");
    var element = document.getElementById("navbar");
    element.classList.toggle("navbar-dark");
    var element = document.getElementById("themebox");
    element.classList.toggle("themebox-dark");
    var element = document.getElementById("box-1001");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1001");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1002");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1002");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1003");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1003");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1004");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1004");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1005");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1005");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1006");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1006");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1007");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1007");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1008");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1008");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1009");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1009");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1010");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1010");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1011");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1011");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1012");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1012");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1013");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1013");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1014");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1014");
    element.classList.toggle("mainhead-dark");
    var element = document.getElementById("box-1015");
    element.classList.toggle("box-dark");
    var element = document.getElementById("mainhead-1015");
    element.classList.toggle("mainhead-dark");
}